# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='flask-sketch',
    version='0.2.2',
    description='A CLI for autogenerate folder structure for Flask applications',
    python_requires='<4.0,>=3.7',
    author='Eric Souza',
    author_email='ericsouza0801@gmail.com',
    license='MIT License',
    entry_points={
        "console_scripts": [
            "flask-sketch = flask_sketch.__main__:flask_sketch"
        ]
    },
    packages=['flask_sketch'],
    package_dir={"": "."},
    package_data={},
    install_requires=['pyfiglet==0.*,>=0.8.0', 'pyinquirer==1.*,>=1.0.3'],
    extras_require={
        "dev": [
            "black==19.*,>=19.10.0.b0", "flake8==3.*,>=3.8.3",
            "flask==1.*,>=1.1.2", "flask-admin==1.*,>=1.5.6",
            "flask-basicauth==0.*,>=0.2.0", "flask-caching==1.*,>=1.9.0",
            "flask-limiter==1.*,>=1.3.1", "flask-migrate==2.*,>=2.5.3",
            "flask-praetorian==1.*,>=1.0.0", "flask-restx==0.*,>=0.2.0",
            "flask-sqlalchemy==2.*,>=2.4.4", "psutil==5.*,>=5.7.2",
            "pyctuator==0.*,>=0.12.0", "python-dotenv==0.*,>=0.14.0"
        ]
    },
)
