# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='flask-sketch',
    version='0.2.2',
    description='A CLI for autogenerate folder structure for Flask applications',
    python_requires='<4.0,>=3.7',
    author='Eric Souza',
    author_email='ericsouza0801@gmail.com',
    license='MIT License',
    entry_points={
        "console_scripts": [
            "flask-sketch = flask_sketch.__main__:flask_sketch"
        ]
    },
    packages=[
        'flask_sketch', 'flask_sketch.handlers', 'flask_sketch.templates',
        'flask_sketch.templates.ext'
    ],
    package_dir={"": "."},
    package_data={},
    install_requires=['pyfiglet==0.*,>=0.8.0', 'pyinquirer==1.*,>=1.0.3'],
    extras_require={
        "dev": ["black==19.*,>=19.10.0.b0", "flake8==3.*,>=3.8.3"]},
)
